project:
  type: book
  output-dir: docs
  
book:

  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - prob.qmd
    - inference.qmd
    - reg.qmd
    - references.qmd

bibliography: references.bib
csl: https://www.zotero.org/styles/associacao-brasileira-de-normas-tecnicas # Opcional: para normas ABNT

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
  pdf:
    documentclass: scrreprt
    pdf-engine: xelatex
    lang: pt-br
    include-in-header: macros.tex
    include-before-body: cover.tex

editor: visual











